"""
BundlePackager — assembles delivery bundles for each pricing tier.

A bundle is a zip archive containing:
  data/            — tier-appropriate CSV or Parquet data files
  LICENSE.md       — usage terms for the purchased tier
  README.md        — field definitions and sample queries
  MANIFEST.json    — metadata (checksums, row counts, date, tier)

Tier definitions are read from config.yaml.
Data files are sourced from data/samples/ (pre-generated by SampleGenerator).
"""

import hashlib
import json
import logging
import zipfile
from datetime import date
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).parent.parent.parent
CONFIG_PATH  = Path(__file__).parent / "config.yaml"
SAMPLES_DIR  = PROJECT_ROOT / "data" / "samples"
BUNDLES_DIR  = PROJECT_ROOT / "releases" / "bundles"

# Files that belong in each tier bundle (matched by glob against SAMPLES_DIR)
_TIER_FILE_PATTERNS: dict[str, list[str]] = {
    "explorer":     ["public/*.csv"],
    "starter":      ["public/*.csv", "paid_tier_1/*.parquet", "paid_tier_1/*.csv"],
    "professional": ["public/*.csv", "paid_tier_1/*.parquet", "paid_tier_1/*.csv",
                     "paid_tier_2/*.parquet"],
    "enterprise":   ["public/*.csv", "paid_tier_1/*.parquet", "paid_tier_1/*.csv",
                     "paid_tier_2/*.parquet"],
}

_LICENSE_TEMPLATES: dict[str, str] = {
    "explorer": """\
# Explorer License — TickerTruth Reference Data

This dataset is provided free of charge for evaluation purposes only.

**Permitted:**
- Personal use and internal evaluation
- Non-commercial research and academic analysis

**Not permitted:**
- Commercial use without a paid subscription
- Redistribution or resale of data
- Use in production trading or risk systems

Full terms: contact@tickertruth.com
""",
    "starter": """\
# Starter License — TickerTruth Reference Data

This dataset is licensed for use by the purchasing organization only.

**Permitted:**
- Internal backtesting and research
- Building analytics dashboards for internal use
- Academic publication with attribution

**Not permitted:**
- Redistribution or resale to third parties
- Embedding data in commercial products sold to others
- Sharing access credentials

Full terms: contact@tickertruth.com | License valid for 12 months from purchase date.
""",
    "professional": """\
# Professional License — TickerTruth Reference Data

This dataset is licensed for production use by the purchasing organization.

**Permitted:**
- Production quant systems and trading infrastructure
- Broker research platforms (internal distribution)
- Integration into commercial products (with separate OEM agreement)

**Not permitted:**
- Direct resale of raw data
- Public redistribution without written consent

Full terms and OEM pricing: contact@tickertruth.com
""",
    "enterprise": """\
# Enterprise License — TickerTruth Reference Data

Custom terms apply per the signed Enterprise Agreement.

For questions about permitted use, contact your account manager.

contact@tickertruth.com
""",
}


class BundlePackager:
    """
    Assembles and zips delivery bundles for a given tier and run date.

    Usage:
        packager = BundlePackager()
        path = packager.build_bundle("starter", date.today())
    """

    def __init__(
        self,
        config_path: Path = CONFIG_PATH,
        samples_dir: Path = SAMPLES_DIR,
        bundles_dir: Path = BUNDLES_DIR,
    ):
        self.samples_dir = Path(samples_dir)
        self.bundles_dir = Path(bundles_dir)
        self.config      = self._load_config(config_path)

    @staticmethod
    def _load_config(path: Path) -> dict:
        with open(path) as fh:
            return yaml.safe_load(fh)

    # ── public API ────────────────────────────────────────────────────────────

    def build_bundle(self, tier: str, run_date: date) -> Path:
        """
        Assemble a complete delivery bundle for the given tier and date.

        Args:
            tier:     One of explorer | starter | professional | enterprise
            run_date: Release date (used to select matching sample files)

        Returns:
            Path to the written zip file.

        Raises:
            ValueError if tier is unknown.
            FileNotFoundError if no data files are found for the tier.
        """
        if tier not in _TIER_FILE_PATTERNS:
            raise ValueError(
                f"Unknown tier '{tier}'. Valid: {list(_TIER_FILE_PATTERNS)}"
            )

        self.bundles_dir.mkdir(parents=True, exist_ok=True)
        date_str  = run_date.strftime("%Y%m%d")
        zip_path  = self.bundles_dir / f"tickertruth_{tier}_{date_str}.zip"

        data_files = self._collect_data_files(tier, run_date)
        if not data_files:
            raise FileNotFoundError(
                f"No data files found for tier '{tier}' on {run_date}. "
                "Run SampleGenerator first."
            )

        manifest = self._build_manifest(tier, run_date, data_files)

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            # Data files
            for src_path in data_files:
                arcname = f"data/{src_path.name}"
                zf.write(src_path, arcname)
                logger.debug("Added %s → %s", src_path.name, arcname)

            # License
            license_text = _LICENSE_TEMPLATES.get(tier, _LICENSE_TEMPLATES["starter"])
            zf.writestr("LICENSE.md", license_text)

            # README
            readme = self._build_readme(tier, run_date, data_files)
            zf.writestr("README.md", readme)

            # Sample queries
            if self.config.get("bundle", {}).get("include_sample_queries", True):
                queries = self._build_sample_queries(tier)
                zf.writestr("sample_queries.sql", queries)

            # Manifest
            zf.writestr("MANIFEST.json", json.dumps(manifest, indent=2))

        logger.info(
            "Bundle created: %s  (%d data files, %.1f KB)",
            zip_path.name,
            len(data_files),
            zip_path.stat().st_size / 1024,
        )
        return zip_path

    def list_tiers(self) -> list[str]:
        """Return all configured tier names."""
        return list(self.config.get("tiers", {}).keys())

    def tier_config(self, tier: str) -> dict:
        """Return configuration dict for a tier."""
        tiers = self.config.get("tiers", {})
        if tier not in tiers:
            raise ValueError(f"Unknown tier '{tier}'")
        return tiers[tier]

    # ── internal helpers ──────────────────────────────────────────────────────

    def _collect_data_files(self, tier: str, run_date: date) -> list[Path]:
        """Glob data files for the tier from samples_dir, filtered by run_date."""
        date_str = run_date.strftime("%Y%m%d")
        patterns = _TIER_FILE_PATTERNS.get(tier, [])
        files: list[Path] = []
        for pattern in patterns:
            for path in self.samples_dir.glob(pattern):
                # Include files matching the run date OR undated sample files
                if date_str in path.stem or not any(
                    c.isdigit() for c in path.stem[-8:]
                ):
                    files.append(path)
        # Deduplicate (a file may match multiple patterns)
        return sorted(set(files))

    def _build_manifest(
        self, tier: str, run_date: date, data_files: list[Path]
    ) -> dict:
        """Build the MANIFEST.json metadata dict."""
        files_meta = []
        for path in data_files:
            checksum = self._sha256(path)
            files_meta.append({
                "filename":  path.name,
                "size_bytes": path.stat().st_size,
                "sha256":    checksum,
            })
        tier_cfg = self.config.get("tiers", {}).get(tier, {})
        return {
            "product":    "TickerTruth NSE Symbol History & Corporate Actions",
            "tier":       tier,
            "tier_label": tier_cfg.get("label", tier),
            "run_date":   run_date.isoformat(),
            "files":      files_meta,
            "contact":    "contact@tickertruth.com",
        }

    @staticmethod
    def _build_readme(tier: str, run_date: date, data_files: list[Path]) -> str:
        filelist = "\n".join(f"- `data/{f.name}`" for f in data_files)
        return f"""\
# TickerTruth — NSE Symbol History & Corporate Actions

**Tier:** {tier.title()}
**Release date:** {run_date.isoformat()}

## Contents

{filelist}
- `LICENSE.md` — usage terms
- `sample_queries.sql` — example SQL queries
- `MANIFEST.json` — checksums and metadata

## Key columns

| Column | Description |
|---|---|
| `nse_symbol` | NSE trading symbol (normalised, no series suffix) |
| `isin` | 12-character ISIN — stable identifier across renames |
| `action_code` | Corporate action type (SPLIT, BONUS, DIVIDEND, …) |
| `event_date` | Ex-date for corporate actions |
| `total_adjustment_factor` | Cumulative price multiplier for backtesting |
| `confidence_score` | 0.0–1.0 data quality score |

## Verification

```bash
# Verify file integrity (Linux/macOS)
sha256sum -c MANIFEST.json  # or check manually against MANIFEST.json
```

## Support

contact@tickertruth.com — include your buyer ID and tier in subject line.
"""

    @staticmethod
    def _build_sample_queries(tier: str) -> str:
        base = """\
-- TickerTruth Sample Queries
-- Compatible with: Dolt (MySQL), Snowflake, BigQuery, DuckDB

-- 1. All active securities
SELECT nse_symbol, isin, company_name, sector, listing_date
FROM dim_security_master
WHERE active_flag = TRUE
ORDER BY listing_date DESC;

-- 2. Corporate actions for a symbol
SELECT action_code, event_date, old_value, confidence_score
FROM fact_corporate_action_event
WHERE security_id = (
    SELECT security_id FROM dim_security_master WHERE nse_symbol = 'INFY'
)
ORDER BY event_date DESC;

-- 3. Backtest-adjusted price calculation
SELECT
    e.trading_date,
    e.close_price,
    f.total_adjustment_factor,
    e.close_price * f.total_adjustment_factor AS adjusted_close
FROM fact_equity_eod e
JOIN fact_adjustment_factor f
  ON e.security_id = f.security_id
 AND e.trading_date >= f.as_of_date
WHERE e.security_id = (
    SELECT security_id FROM dim_security_master WHERE nse_symbol = 'RELIANCE'
)
ORDER BY e.trading_date;
"""
        if tier in ("professional", "enterprise"):
            base += """
-- 4. Symbol rename history (Professional/Enterprise only)
SELECT old_symbol, new_symbol, event_date, confidence
FROM fact_symbol_lineage_event
WHERE event_type = 'RENAME'
ORDER BY event_date DESC;

-- 5. Symbols with low data confidence (for review)
SELECT security_id, action_code, event_date, confidence_score
FROM fact_corporate_action_event
WHERE confidence_score < 0.7
ORDER BY confidence_score;
"""
        return base

    @staticmethod
    def _sha256(path: Path) -> str:
        h = hashlib.sha256()
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
