"""
WarehouseExporter — generates DDL and adapted sample queries for cloud
data warehouse migration (Snowflake, BigQuery, Databricks/Delta).

Preserves the TickerTruth schema so buyers can load data into their own warehouse
without re-engineering the model. Keeps export logic decoupled from delivery.

Output: data/warehouse/{target}/  containing:
  schema.sql       — CREATE TABLE / CREATE SCHEMA statements
  sample_queries.sql — adapted view queries
  field_catalog.md — human-readable field documentation
"""

import logging
from datetime import date
from pathlib import Path

logger = logging.getLogger(__name__)

PROJECT_ROOT  = Path(__file__).parent.parent.parent
WAREHOUSE_DIR = PROJECT_ROOT / "data" / "warehouse"

SUPPORTED_TARGETS = ("snowflake", "bigquery", "databricks", "duckdb")


class WarehouseExporter:
    """
    Generates warehouse-specific DDL and query files from the TickerTruth schema.

    Usage:
        exp = WarehouseExporter()
        exp.export("snowflake")
        exp.export("bigquery")
        exp.export_all()
    """

    def __init__(self, output_dir: Path = WAREHOUSE_DIR):
        self.output_dir = Path(output_dir)

    def export_all(self) -> dict[str, list[Path]]:
        """Export DDL and queries for all supported targets."""
        results = {}
        for target in SUPPORTED_TARGETS:
            results[target] = self.export(target)
        return results

    def export(self, target: str) -> list[Path]:
        """
        Generate DDL, queries, and field catalog for a target warehouse.

        Args:
            target: One of snowflake | bigquery | databricks | duckdb

        Returns:
            List of paths to generated files.
        """
        if target not in SUPPORTED_TARGETS:
            raise ValueError(
                f"Unknown target '{target}'. Supported: {SUPPORTED_TARGETS}"
            )

        out_dir = self.output_dir / target
        out_dir.mkdir(parents=True, exist_ok=True)

        paths = []
        ddl_fn   = getattr(self, f"_ddl_{target}")
        query_fn = getattr(self, f"_queries_{target}", self._queries_generic)

        schema_path = out_dir / "schema.sql"
        schema_path.write_text(ddl_fn())
        paths.append(schema_path)

        queries_path = out_dir / "sample_queries.sql"
        queries_path.write_text(query_fn())
        paths.append(queries_path)

        catalog_path = out_dir / "field_catalog.md"
        catalog_path.write_text(self._field_catalog(target))
        paths.append(catalog_path)

        logger.info(
            "Warehouse export complete: %s  (%d files in %s)",
            target, len(paths), out_dir,
        )
        return paths

    # ── DDL generators ────────────────────────────────────────────────────────

    def _ddl_snowflake(self) -> str:
        return """\
-- TickerTruth Schema — Snowflake DDL
-- Generated by WarehouseExporter
-- Differences from MySQL source:
--   AUTO_INCREMENT → AUTOINCREMENT
--   ENUM           → VARCHAR
--   BOOLEAN        → BOOLEAN (native)
--   FK constraints declared but not enforced in Snowflake

CREATE DATABASE IF NOT EXISTS tickertruth;
USE DATABASE tickertruth;
CREATE SCHEMA IF NOT EXISTS reference;
USE SCHEMA reference;

-- ── Dimension Tables ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS dim_exchange (
    exchange_id     INTEGER PRIMARY KEY,
    exchange_code   VARCHAR(10)  NOT NULL UNIQUE,
    exchange_name   VARCHAR(100) NOT NULL,
    country         VARCHAR(50)  NOT NULL,
    created_at      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS dim_issuer (
    issuer_id           INTEGER AUTOINCREMENT PRIMARY KEY,
    issuer_name         VARCHAR(255) NOT NULL UNIQUE,
    sector              VARCHAR(100),
    market_cap_category VARCHAR(50),
    country             VARCHAR(50) NOT NULL DEFAULT 'India',
    created_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS dim_security_master (
    security_id  INTEGER AUTOINCREMENT PRIMARY KEY,
    nse_symbol   VARCHAR(50)  NOT NULL UNIQUE,
    isin         VARCHAR(12),
    company_name VARCHAR(255) NOT NULL,
    issuer_id    INTEGER      NOT NULL,
    exchange_id  INTEGER      NOT NULL,
    listing_date DATE,
    active_flag  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS dim_symbol_alias (
    alias_id       INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id    INTEGER     NOT NULL,
    symbol         VARCHAR(50) NOT NULL,
    alias_type     VARCHAR(20) NOT NULL,  -- current | historical | alternate
    effective_from DATE        NOT NULL,
    effective_to   DATE,
    created_at     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS dim_corporate_action_type (
    action_type_id INTEGER AUTOINCREMENT PRIMARY KEY,
    action_code    VARCHAR(50)  NOT NULL UNIQUE,
    action_name    VARCHAR(255) NOT NULL,
    description    TEXT,
    created_at     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── Fact Tables ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS fact_equity_eod (
    eod_id       INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id  INTEGER NOT NULL,
    trading_date DATE    NOT NULL,
    open_price   NUMBER(10, 2),
    high_price   NUMBER(10, 2),
    low_price    NUMBER(10, 2),
    close_price  NUMBER(10, 2) NOT NULL,
    volume       BIGINT,
    created_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (security_id, trading_date)
);

CREATE TABLE IF NOT EXISTS fact_corporate_action_event (
    event_id         INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id      INTEGER NOT NULL,
    action_type_id   INTEGER NOT NULL,
    event_date       DATE    NOT NULL,
    record_date      DATE,
    payment_date     DATE,
    old_value        NUMBER(15, 6),
    new_value        NUMBER(15, 6),
    adjustment_factor NUMBER(15, 6),
    description      TEXT,
    source           VARCHAR(100),
    confidence_score NUMBER(3, 2) DEFAULT 1.0,
    created_at       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS fact_adjustment_factor (
    adjustment_id                 INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id                   INTEGER       NOT NULL,
    as_of_date                    DATE          NOT NULL,
    cumulative_split_adjustment   NUMBER(15, 6) NOT NULL DEFAULT 1.0,
    cumulative_dividend_adjustment NUMBER(15, 6) NOT NULL DEFAULT 1.0,
    cumulative_bonus_adjustment   NUMBER(15, 6) NOT NULL DEFAULT 1.0,
    total_adjustment_factor       NUMBER(15, 6) NOT NULL DEFAULT 1.0,
    created_at                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (security_id, as_of_date)
);

CREATE TABLE IF NOT EXISTS fact_symbol_lineage_event (
    lineage_id          INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id         INTEGER     NOT NULL,
    old_symbol          VARCHAR(50),
    new_symbol          VARCHAR(50),
    change_date         DATE        NOT NULL,
    change_reason       VARCHAR(20) NOT NULL,  -- rename|merger|split|delisting|relisting
    merged_with_symbol  VARCHAR(50),
    source              VARCHAR(100),
    created_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS fact_listing_status_history (
    status_id      INTEGER AUTOINCREMENT PRIMARY KEY,
    security_id    INTEGER     NOT NULL,
    status         VARCHAR(20) NOT NULL,  -- active|suspended|delisted|relisted
    effective_date DATE        NOT NULL,
    reason         TEXT,
    created_at     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
"""

    def _ddl_bigquery(self) -> str:
        return """\
-- TickerTruth Schema — BigQuery DDL
-- Generated by WarehouseExporter
-- Differences from MySQL source:
--   AUTO_INCREMENT     → no equivalent; use INT64 + sequence or GENERATE_UUID()
--   BOOLEAN            → BOOL
--   DECIMAL/NUMBER     → NUMERIC or FLOAT64
--   ENUM               → STRING (validated by application layer)
--   TIMESTAMP          → TIMESTAMP (UTC)
--   FOREIGN KEYs       → omitted (not enforced in BigQuery)
--   UNIQUE constraints → omitted (not enforced in BigQuery)

-- Replace `your_project.tickertruth` with your actual project.dataset path.

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.dim_exchange` (
    exchange_id   INT64   NOT NULL,
    exchange_code STRING  NOT NULL,
    exchange_name STRING  NOT NULL,
    country       STRING  NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.dim_issuer` (
    issuer_id           INT64  NOT NULL,
    issuer_name         STRING NOT NULL,
    sector              STRING,
    market_cap_category STRING,
    country             STRING NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.dim_security_master` (
    security_id  INT64   NOT NULL,
    nse_symbol   STRING  NOT NULL,
    isin         STRING,
    company_name STRING  NOT NULL,
    issuer_id    INT64   NOT NULL,
    exchange_id  INT64   NOT NULL,
    listing_date DATE,
    active_flag  BOOL    NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.dim_symbol_alias` (
    alias_id       INT64  NOT NULL,
    security_id    INT64  NOT NULL,
    symbol         STRING NOT NULL,
    alias_type     STRING NOT NULL,
    effective_from DATE   NOT NULL,
    effective_to   DATE
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.dim_corporate_action_type` (
    action_type_id INT64  NOT NULL,
    action_code    STRING NOT NULL,
    action_name    STRING NOT NULL,
    description    STRING
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.fact_equity_eod` (
    eod_id       INT64   NOT NULL,
    security_id  INT64   NOT NULL,
    trading_date DATE    NOT NULL,
    open_price   NUMERIC,
    high_price   NUMERIC,
    low_price    NUMERIC,
    close_price  NUMERIC NOT NULL,
    volume       INT64,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.fact_corporate_action_event` (
    event_id          INT64   NOT NULL,
    security_id       INT64   NOT NULL,
    action_type_id    INT64   NOT NULL,
    event_date        DATE    NOT NULL,
    record_date       DATE,
    payment_date      DATE,
    old_value         NUMERIC,
    new_value         NUMERIC,
    adjustment_factor NUMERIC,
    description       STRING,
    source            STRING,
    confidence_score  NUMERIC
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.fact_adjustment_factor` (
    adjustment_id                  INT64   NOT NULL,
    security_id                    INT64   NOT NULL,
    as_of_date                     DATE    NOT NULL,
    cumulative_split_adjustment    NUMERIC NOT NULL,
    cumulative_dividend_adjustment NUMERIC NOT NULL,
    cumulative_bonus_adjustment    NUMERIC NOT NULL,
    total_adjustment_factor        NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS `your_project.tickertruth.fact_symbol_lineage_event` (
    lineage_id         INT64  NOT NULL,
    security_id        INT64  NOT NULL,
    old_symbol         STRING,
    new_symbol         STRING,
    change_date        DATE   NOT NULL,
    change_reason      STRING NOT NULL,
    merged_with_symbol STRING,
    source             STRING
);
"""

    def _ddl_databricks(self) -> str:
        return """\
-- TickerTruth Schema — Databricks / Delta Lake DDL
-- Generated by WarehouseExporter
-- Uses Delta format; replace `tickertruth` with your catalog/schema.

CREATE DATABASE IF NOT EXISTS tickertruth;
USE tickertruth;

CREATE TABLE IF NOT EXISTS dim_exchange (
    exchange_id   INT     NOT NULL,
    exchange_code STRING  NOT NULL,
    exchange_name STRING  NOT NULL,
    country       STRING  NOT NULL,
    created_at    TIMESTAMP DEFAULT current_timestamp()
) USING DELTA;

CREATE TABLE IF NOT EXISTS dim_issuer (
    issuer_id           BIGINT NOT NULL,
    issuer_name         STRING NOT NULL,
    sector              STRING,
    market_cap_category STRING,
    country             STRING NOT NULL,
    created_at          TIMESTAMP DEFAULT current_timestamp()
) USING DELTA;

CREATE TABLE IF NOT EXISTS dim_security_master (
    security_id  BIGINT  NOT NULL,
    nse_symbol   STRING  NOT NULL,
    isin         STRING,
    company_name STRING  NOT NULL,
    issuer_id    BIGINT  NOT NULL,
    exchange_id  INT     NOT NULL,
    listing_date DATE,
    active_flag  BOOLEAN NOT NULL
) USING DELTA;

CREATE TABLE IF NOT EXISTS dim_corporate_action_type (
    action_type_id BIGINT NOT NULL,
    action_code    STRING NOT NULL,
    action_name    STRING NOT NULL,
    description    STRING
) USING DELTA;

CREATE TABLE IF NOT EXISTS fact_equity_eod (
    eod_id       BIGINT  NOT NULL,
    security_id  BIGINT  NOT NULL,
    trading_date DATE    NOT NULL,
    open_price   DECIMAL(10, 2),
    high_price   DECIMAL(10, 2),
    low_price    DECIMAL(10, 2),
    close_price  DECIMAL(10, 2) NOT NULL,
    volume       BIGINT
) USING DELTA
PARTITIONED BY (trading_date);

CREATE TABLE IF NOT EXISTS fact_corporate_action_event (
    event_id          BIGINT         NOT NULL,
    security_id       BIGINT         NOT NULL,
    action_type_id    BIGINT         NOT NULL,
    event_date        DATE           NOT NULL,
    record_date       DATE,
    payment_date      DATE,
    old_value         DECIMAL(15, 6),
    new_value         DECIMAL(15, 6),
    adjustment_factor DECIMAL(15, 6),
    confidence_score  DECIMAL(3, 2)
) USING DELTA
PARTITIONED BY (event_date);

CREATE TABLE IF NOT EXISTS fact_adjustment_factor (
    adjustment_id                  BIGINT         NOT NULL,
    security_id                    BIGINT         NOT NULL,
    as_of_date                     DATE           NOT NULL,
    cumulative_split_adjustment    DECIMAL(15, 6) NOT NULL,
    cumulative_dividend_adjustment DECIMAL(15, 6) NOT NULL,
    cumulative_bonus_adjustment    DECIMAL(15, 6) NOT NULL,
    total_adjustment_factor        DECIMAL(15, 6) NOT NULL
) USING DELTA;

CREATE TABLE IF NOT EXISTS fact_symbol_lineage_event (
    lineage_id         BIGINT NOT NULL,
    security_id        BIGINT NOT NULL,
    old_symbol         STRING,
    new_symbol         STRING,
    change_date        DATE   NOT NULL,
    change_reason      STRING NOT NULL,
    merged_with_symbol STRING,
    source             STRING
) USING DELTA;
"""

    def _ddl_duckdb(self) -> str:
        return """\
-- TickerTruth Schema — DuckDB DDL
-- Generated by WarehouseExporter
-- DuckDB is closest to standard SQL; minimal changes from MySQL source.
-- Useful for local development and Parquet-based analysis.

CREATE TABLE IF NOT EXISTS dim_exchange (
    exchange_id   INTEGER PRIMARY KEY,
    exchange_code VARCHAR(10)  NOT NULL UNIQUE,
    exchange_name VARCHAR(100) NOT NULL,
    country       VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_issuer (
    issuer_id           INTEGER PRIMARY KEY,
    issuer_name         VARCHAR(255) NOT NULL UNIQUE,
    sector              VARCHAR(100),
    market_cap_category VARCHAR(50),
    country             VARCHAR(50) NOT NULL DEFAULT 'India',
    created_at          TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_security_master (
    security_id  INTEGER PRIMARY KEY,
    nse_symbol   VARCHAR(50)  NOT NULL UNIQUE,
    isin         VARCHAR(12),
    company_name VARCHAR(255) NOT NULL,
    issuer_id    INTEGER      NOT NULL REFERENCES dim_issuer(issuer_id),
    exchange_id  INTEGER      NOT NULL REFERENCES dim_exchange(exchange_id),
    listing_date DATE,
    active_flag  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_corporate_action_type (
    action_type_id INTEGER PRIMARY KEY,
    action_code    VARCHAR(50)  NOT NULL UNIQUE,
    action_name    VARCHAR(255) NOT NULL,
    description    TEXT
);

CREATE TABLE IF NOT EXISTS fact_equity_eod (
    eod_id       INTEGER PRIMARY KEY,
    security_id  INTEGER      NOT NULL REFERENCES dim_security_master(security_id),
    trading_date DATE         NOT NULL,
    open_price   DECIMAL(10, 2),
    high_price   DECIMAL(10, 2),
    low_price    DECIMAL(10, 2),
    close_price  DECIMAL(10, 2) NOT NULL,
    volume       BIGINT,
    UNIQUE (security_id, trading_date)
);

CREATE TABLE IF NOT EXISTS fact_corporate_action_event (
    event_id          INTEGER PRIMARY KEY,
    security_id       INTEGER NOT NULL REFERENCES dim_security_master(security_id),
    action_type_id    INTEGER NOT NULL REFERENCES dim_corporate_action_type(action_type_id),
    event_date        DATE    NOT NULL,
    record_date       DATE,
    payment_date      DATE,
    old_value         DECIMAL(15, 6),
    new_value         DECIMAL(15, 6),
    adjustment_factor DECIMAL(15, 6),
    confidence_score  DECIMAL(3, 2) DEFAULT 1.0
);

CREATE TABLE IF NOT EXISTS fact_adjustment_factor (
    adjustment_id                  INTEGER PRIMARY KEY,
    security_id                    INTEGER        NOT NULL REFERENCES dim_security_master(security_id),
    as_of_date                     DATE           NOT NULL,
    cumulative_split_adjustment    DECIMAL(15, 6) NOT NULL DEFAULT 1.0,
    cumulative_dividend_adjustment DECIMAL(15, 6) NOT NULL DEFAULT 1.0,
    cumulative_bonus_adjustment    DECIMAL(15, 6) NOT NULL DEFAULT 1.0,
    total_adjustment_factor        DECIMAL(15, 6) NOT NULL DEFAULT 1.0,
    UNIQUE (security_id, as_of_date)
);

CREATE TABLE IF NOT EXISTS fact_symbol_lineage_event (
    lineage_id         INTEGER PRIMARY KEY,
    security_id        INTEGER     NOT NULL REFERENCES dim_security_master(security_id),
    old_symbol         VARCHAR(50),
    new_symbol         VARCHAR(50),
    change_date        DATE        NOT NULL,
    change_reason      VARCHAR(20) NOT NULL,
    merged_with_symbol VARCHAR(50),
    source             VARCHAR(100)
);

-- DuckDB: load Parquet directly (no import step needed)
-- Example:
--   INSERT INTO dim_security_master
--   SELECT * FROM read_parquet('full_security_master_20260601.parquet');
"""

    # ── query generators ──────────────────────────────────────────────────────

    def _queries_snowflake(self) -> str:
        return self._queries_generic().replace(
            "CURDATE()", "CURRENT_DATE()"
        ).replace(
            "INTERVAL 365 DAY", "DATEADD(day, -365, CURRENT_DATE())"
        )

    def _queries_bigquery(self) -> str:
        return self._queries_generic().replace(
            "CURDATE()", "CURRENT_DATE()"
        ).replace(
            "dim_security_master", "`your_project.tickertruth.dim_security_master`"
        ).replace(
            "fact_corporate_action_event", "`your_project.tickertruth.fact_corporate_action_event`"
        ).replace(
            "fact_adjustment_factor", "`your_project.tickertruth.fact_adjustment_factor`"
        ).replace(
            "fact_equity_eod", "`your_project.tickertruth.fact_equity_eod`"
        )

    def _queries_databricks(self) -> str:
        return self._queries_generic().replace(
            "CURDATE()", "current_date()"
        )

    def _queries_duckdb(self) -> str:
        return self._queries_generic().replace(
            "CURDATE()", "current_date"
        ).replace(
            "INTERVAL 365 DAY", "INTERVAL 365 DAYS"
        )

    @staticmethod
    def _queries_generic() -> str:
        return """\
-- TickerTruth Sample Queries
-- Replace CURDATE() / table prefixes as needed for your target warehouse.

-- 1. Current active securities with issuer info
SELECT
    sm.nse_symbol,
    sm.isin,
    sm.company_name,
    di.sector,
    sm.listing_date
FROM dim_security_master sm
JOIN dim_issuer di ON sm.issuer_id = di.issuer_id
WHERE sm.active_flag = TRUE
ORDER BY sm.listing_date DESC;

-- 2. All corporate actions for a specific symbol
SELECT
    cat.action_code,
    ca.event_date,
    ca.old_value,
    ca.confidence_score
FROM fact_corporate_action_event ca
JOIN dim_corporate_action_type cat ON ca.action_type_id = cat.action_type_id
WHERE ca.security_id = (
    SELECT security_id FROM dim_security_master WHERE nse_symbol = 'INFY'
)
ORDER BY ca.event_date DESC;

-- 3. Backtest-ready adjusted price series
SELECT
    sm.nse_symbol,
    e.trading_date,
    e.close_price                                    AS raw_close,
    e.close_price * f.total_adjustment_factor        AS adj_close,
    f.total_adjustment_factor
FROM fact_equity_eod e
JOIN dim_security_master sm ON e.security_id = sm.security_id
JOIN fact_adjustment_factor f
  ON e.security_id = f.security_id
 AND e.trading_date >= f.as_of_date
WHERE sm.nse_symbol = 'RELIANCE'
ORDER BY e.trading_date;

-- 4. Symbols that changed name or ticker
SELECT
    old_symbol,
    new_symbol,
    change_date,
    change_reason
FROM fact_symbol_lineage_event
WHERE change_reason IN ('rename', 'merger')
ORDER BY change_date DESC;

-- 5. Quality filter: high-confidence actions only
SELECT
    sm.nse_symbol,
    cat.action_code,
    ca.event_date,
    ca.old_value
FROM fact_corporate_action_event ca
JOIN dim_security_master sm ON ca.security_id = sm.security_id
JOIN dim_corporate_action_type cat ON ca.action_type_id = cat.action_type_id
WHERE ca.confidence_score >= 0.9
  AND ca.event_date >= CURDATE() - INTERVAL 365 DAY
ORDER BY ca.event_date DESC;
"""

    # ── field catalog ─────────────────────────────────────────────────────────

    @staticmethod
    def _field_catalog(target: str) -> str:
        return f"""\
# TickerTruth Field Catalog — {target.title()}

## dim_security_master

| Field | Type | Description |
|---|---|---|
| `security_id` | integer | Surrogate key |
| `nse_symbol` | string | NSE trading symbol (normalised, no series suffix) |
| `isin` | string | 12-char ISIN — stable across renames |
| `company_name` | string | Canonical company name (normalised to uppercase) |
| `issuer_id` | integer | FK → dim_issuer |
| `exchange_id` | integer | FK → dim_exchange (1 = NSE) |
| `listing_date` | date | First trading date on NSE |
| `active_flag` | bool | True = currently trading |

## fact_corporate_action_event

| Field | Type | Description |
|---|---|---|
| `security_id` | integer | FK → dim_security_master |
| `action_type_id` | integer | FK → dim_corporate_action_type |
| `event_date` | date | Ex-date (first day without entitlement) |
| `record_date` | date | Cutoff date for shareholders of record |
| `payment_date` | date | Date benefits are credited |
| `old_value` | decimal | Ratio or amount (e.g. 0.5 for 1:2 split, 5.0 for ₹5 dividend) |
| `adjustment_factor` | decimal | Pre-computed price multiplier |
| `confidence_score` | decimal | 0.0–1.0 data quality score |

## fact_adjustment_factor

| Field | Type | Description |
|---|---|---|
| `security_id` | integer | FK → dim_security_master |
| `as_of_date` | date | Date from which this cumulative factor applies |
| `cumulative_split_adjustment` | decimal | Running split factor (< 1 means prices were higher pre-split) |
| `cumulative_bonus_adjustment` | decimal | Running bonus factor |
| `total_adjustment_factor` | decimal | Split × bonus — multiply raw close to get adjusted close |

## fact_symbol_lineage_event

| Field | Type | Description |
|---|---|---|
| `old_symbol` | string | Previous trading symbol (null for new listings) |
| `new_symbol` | string | New trading symbol (null for delistings) |
| `change_date` | date | Effective date of the change |
| `change_reason` | string | rename \\| merger \\| split \\| delisting \\| relisting |
| `merged_with_symbol` | string | Absorbing symbol for mergers |

## Notes on adjustment_factor usage

To compute backtest-adjusted prices:
```sql
adjusted_close = raw_close * total_adjustment_factor
```

The factor is cumulative from inception — apply it uniformly to all historical
prices before the `as_of_date` event to get a continuous adjusted series.
"""
